- .github/workflows/yaml-lint.yml
- .yamllint.yml
- cleanup/action.yml
- setup-venv/action.yml
- setup-venv/readme.md
Made as a (partial) replacement for https://github.com/actions/setup-python,
particularly for using on ARM64 machines, where setup-python doesn't work.
Sometimes we don't need to set up the exact version of Python, but rather
need to set up a virtual environment and install a few packages in it.
If `virtualenv` is not found in the system, this action will install it
with `pip install --user`. This way it will not interfere with
system Python packages.
Resolve #3
> Setup Python virtual environment with an action

- update-submodule/README.md
- update-submodule/action.yml
This patch refines parameters of the `update-submodule` action: removes
redundant and makes remaining consistent.
Also, it removes some hard-coded stuff (e.g PR title, commit message).
Now the PR title can be fully configured by users, the commit message
can be defined by users as well.
Also, now we can specify a submodule path that we would like to update.
Moreover, we can update a few or all submodules.
We should give users max flexibility on use of the action.
> Refine params of `update-submodule` action

- update-submodule/action.yml
Sometimes it is needed to provide the pull request description different
from the pull request title. The new `pr_description` option is exactly
intended for such cases.
> Add `pr_description` to update-submodule action

- update-submodule/action.yml
This patch fixes the following bug: the action always updated the given
submodule to the last commit from the `master` branch.
Sometimes we need to update the submodule to the version from a branch
different from `master` and this change provides such an ability.
> Fix always-update to master in `update-submodule`

- report-job-status/README.md
- report-job-status/action.yml
When someone doesn't specify a value for the `job-steps` parameter,
the action fails with the `SyntaxError: Unexpected token 'const'` error.
> report-job-status: add default val for `job-steps`

- report-job-status/action.yml
The previous logic on building the branch link was incorrect because
the `branch = ref.split("/")[2]` expression did not work as expected
when the branch was named, for example, `someone/feature-1`. So we had
the corrupted link in the message. Moreover, if the ref was a tag, the
link was incorrect as well. Now these two cases are considered.
> report-job-status: fix branch link in message

- report-job-status/README.md
- report-job-status/action.yml
This patch sets the default value for the `api-url` so the action
won't fail if credidentials for VK Teams are not set. Also this
patch improves code style (rule 80)
> report-job-status: improve inputs and code style

- report-job-status/action.yml
When a commit message had backticks inside, we had the syntax err in JS
due to substituting expression ${{ github.event.head_commit.message }}:
SyntaxError: Unexpected identifier
<...>
Error: Unhandled error: SyntaxError: Unexpected identifier
Now we have a special preparation step where all backticks in the commit
message are masked to avoid this issue.
> report-job-status: mask backticks in commit msg

- report-job-status/README.md
- report-job-status/action.yml
When a workflow is triggered on a pull request or schedule event,
the `${{ github.event.head_commit.message }}` expression is empty
and we have the empty value for the `Commit message subject` field
in the message:
Job failed at tarantool/tarantool:
Job: test
Commit: a179a29bdee013afe8dfd6375d233f5a1e291d22
Branch: 7494/merge
History: commits
Triggered on: pull_request
Committer: ylobankov
Commit message subject:
Now if the value is empty, it is omitted:
Job failed at tarantool/tarantool:
Job: test
Commit: a179a29bdee013afe8dfd6375d233f5a1e291d22
Branch: 7494/merge
History: commits
Triggered on: pull_request
Committer: ylobankov
> report-job-status: don't print commit str if empty

- report-job-status/action.yml
When a workflow was triggered on a pull request event, we should provide
the link to this pull request. The link to the branch was inconvenient,
moreover, the link was wrong.
> report-job-status: provide PR link in message

- report-job-status/README.md
A job step cannot have both `run` and `uses`.
> report-job-status: fix code example in README.md

- report-job-status/action.yml
The link was wrong since there was a space between `${jobId}?` and
`check_suite_focus=true`.
> report-job-status: fix job log link

- cleanup/README.md
- prepare-checkout/README.md
- prepare-checkout/action.yml
Make an empty detached commit for actions/checkout to properly clean the project's workspace before checking out new code revision.
Part of #28
Related to tarantool/tarantool-qa#145
**Readme preview:** https://github.com/tarantool/actions/blob/nickvolynkin/cleanup-with-empty-commit/prepare-checkout/README.md
> cleanup: make an empty commit for actions/checkout

- setup-venv/action.yml
Fixes the following problem:
```
Run if [ -z ~/.local/bin/virtualenv ]; then \
Run ~/.local/bin/virtualenv venv && \
/opt/actions-runner/_work/_temp/50147462-f3e3-4a01-9605-3660a7d39edc.sh:
line 1: /root/.local/bin/virtualenv: No such file or directory
Error: Process completed with exit code 127.
```
> setup-venv: fix condition for virtualenv

- update-submodule/README.md
* Add two diagrams explaining the action's workflow.
* Document input variables `update_to` and `pr_description`.
* Reorder input variables according to the logic of the workflow.
* Add default values for optional variables.
* Reword descriptions of a few variables.
Readme preview: https://github.com/tarantool/actions/tree/nickvolynkin/update-submodule-readme/update-submodule#readme
> update-submodule: add diagrams and refine the readme

- update-submodule/README.md
- update-submodule/action.yml
Set variable `create_pr: false` to skip pull request creation.
Default value is `true`, to keep compatibility with workflows
that are already using this action.
Part of https://github.com/tarantool/sdk/issues/355
>  update-submodule: control PR creation with create_pr variable

- .github/workflows/yaml-lint.yml
- update-submodule/action.yml
Removes the following warning:
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16: actions/checkout@v2, actions/github-script@v5
> deps: update actions to use Node.js 16

- update-submodule/README.md
- update-submodule/action.yml
See https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-composite-actions.
To access the output values, assign an id to the step that is using this action.
Then get the values like this: `${{ steps.<step-id>.outputs.sha }}`.
Resolves #40
---
Testing:  the following action step
```yml
- name: Dump actions/update-submodule outputs
run: echo '${{ toJSON(steps.create-branch.outputs) }}'
```
shows
```
{
"sha": "846617ad9dad04f335feb24792ec57ce37200b62",
"sha7": "846617a"
}
```
> update-submodule: return sha and sha7 in action's outputs

- update-submodule/action.yml
The `git checkout ${{ inputs.update_to }}` expression did not give us the desired result when the target repository was already checked out on a self-hosted runner because in this case we just checked out the local ref. Now we always check out fetched ref.
Fixes #44
> update-submodule: always check out fetched ref

- report-job-status/README.md
Add an example of setting the `job-name` directly
from the `matrix` context, describe the requirements.
Also, slightly format the example values and remove
the misleading `@` from the `chat-id` example.
Preview: https://github.com/tarantool/actions/tree/nickvolynkin/report-job-status-matrix-usage/report-job-status#basic-usage
> report-job-status: improve docs on matrix strategy

- .gitignore
- get-pr-info/action.yml
- get-pr-info/readme.md
- remove-git-ref/action.yml
- remove-git-ref/readme.md
Add the action for retrieving pull request context when it's not
available by default, like in `workflow_dispatch` events that work with
pull requests.
Add an action for removing branches and other refs in
GitHub repositories.
Part of https://github.com/tarantool/tarantool-qa/issues/296
> Actions get-pr-info and remove-git-ref

- update-submodule/action.yml
Sometimes a submodule may be updated by somebody manually, bypassing the action. In such cases the following error occures when the action is running:
On branch <branch name>
nothing to commit, working tree clean
This patch fixes the problem.
> update-submodule: not fail when nothing to commit

- check-module-version/README.md
- check-module-version/action.yml
Added `check-module-version` action for checking the equality of the version from lua module's code and the last repository tag
> check-module-version: add action

- check-module-version/README.md
- check-module-version/action.yml
Added the ability to specify a custom rock make opts via new `inputs.rock-make-opts` action parameter. For example, some packages require command `tarantoolctl rocks STATIC_BUILD=ON make` instead of `tarantoolctl rocks make`.
Is part of the task [1].
1. github.com/tarantool/roadmap-internal/issues/204
> check-module-version: add custom rock make opts

- get-job-id/README.md
- get-job-id/action.yml
- report-job-status/action.yml
- s3-copy/README.md
- s3-copy/action.yml
get-job-id: add the action to get job ID
There are several situations when we need the job ID, but the GitHub
doesn't give the context with the job ID. This patch adds the action
to get the job ID from the jobs' context (info about all the jobs in the
run) with job name and run attempt.
Resolves #56 
_______
s3-copy: add action to save files to S3
This patch adds the s3-copy action to save files, i.e. job artifacts, to the S3 storage with the predictable path for easy access via the link.
Part of tarantool/multivac#116
> s3-copy: add action to save files to S3

- prepare-checkout/README.md
- prepare-checkout/action.yml
This patch adds one more step to the action to delete stale references associated with `origin`. This will not affect local branches, and it will not change anything remote, but it will update the local references to remote branches to avoid errors like this:
error: cannot lock ref 'refs/remotes/origin/<repo>/<branch>': 'refs/remotes/origin/<repo>' exists; cannot create 'refs/remotes/origin/<repo>/<branch>'
! [new branch] <repo>/<branch> -> origin/<repo>/<branch> (unable to update local ref)
However, this can be disabled via the new `prune` option, just set it to `false`.
Note that submodules are affected as well.
> prepare-checkout: delete stale origin references

- setup-etcd/README.md
- setup-etcd/action.yml
This patch adds the setup-etcd action to set up an etcd store from a release archive.
> setup-etcd: add action

- setup-etcd/action.yml
It speeds up the installation and also gives better stability of jobs if the network is not very reliable on a runner.
> setup-etcd: cache etcd binaries

- .github/workflows/yaml-lint.yml
- check-module-version/action.yml
- get-job-id/action.yml
- get-pr-info/action.yml
- remove-git-ref/action.yml
- report-job-status/action.yml
- update-submodule/action.yml
Eliminate the following GitHub warning about deprecated Node.js:
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20
> actions: bump versions to use Node.js 20
